
set( output_dir_properties
    LIBRARY_OUTPUT_DIRECTORY
    LIBRARY_OUTPUT_DIRECTORY_DEBUG
    LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO
    LIBRARY_OUTPUT_DIRECTORY_RELEASE
    RUNTIME_OUTPUT_DIRECTORY
    RUNTIME_OUTPUT_DIRECTORY_DEBUG
    RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO
    RUNTIME_OUTPUT_DIRECTORY_RELEASE
    ARCHIVE_OUTPUT_DIRECTORY
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG
    ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE
)
foreach ( output_dir_property ${output_dir_properties} )
    set_target_properties( ${output_dir_property} "../../dso/" )
endforeach ()
